sudo: required
os:
  - linux
services:
  - docker
language: go

jobs:
  include:
    - stage: build
      script: ./scripts/build.sh
    - stage: test
      script: ./scripts/test.sh
    - stage: deploy
      script: ./scripts/deploy.sh
